---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    tier: db
spec:
  containers:
  - image: preetam6126/mongodb:v5
    name: mongodb
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    ports:
      - containerPort: 27017           
---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb-service
spec:  
  selector:
    name: mongodb
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017  