---
apiVersion: v1
kind: ConfigMaps
metadata:
  name: cart-config
data:
  CATALOGUE_HOST: "http://catalogue:8080"
  REDIS_HOST: "redis"
  # name: mongodb
  # data:
  #   MONGO_URL: "mongodb://mongodb-service:27017/catalogue"
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    name: catalogue
    tier: app
spec:
  containers:
  - image: preetam6126/catalogue:k8
    name: catalogue
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"   
---
apiVersion: v1
kind: Service
metadata: 
  name: catalogue
spec:  
  selector:
    name: catalogue
    tier: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080  