---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    tier: frontend
spec:
  containers:
  - image: preetam6126/webv:5
    name: web
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"   
    ports: 
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: web-service
spec:
  type: LoadBalancer  
  selector:
    name: web
    tier: frontend